---
- name: Create the dumps backup directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name}}/backup"
    state: directory

- name: Create the dump script
  template:
    src: ../templates/mariadb_dump.j2
    dest: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/dump.sh"
    owner: root
    group: root
    mode: '755'

- name: Create a database dump every week
  cron:
    name: "backup {{ application_name }} database"
    weekday: "{{ dump_day }}"
    minute: "0"
    hour: "0"
    job: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/dump.sh"
    user: root
